name: flutter_webview_plugin_example
description: Demonstrates how to use the flutter_webview_plugin plugin.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_webview_plugin:
    path: ../

flutter:
  uses-material-design: true
